In [8]:
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
# py.tools.set_credentials_file(username='rapp.cxs', api_key='55rlfaf8bj')
%matplotlib inline

In [9]:
adage = pd.read_csv('./adage-data/2016_adage-indies_v2.1.csv')

In [10]:
# a typing function, to split agencies into 3 types:
def typer(x):
    if x=="Publicis" or \
       x=="WPP" or \
       x=="Interpublic" or \
       x=="Havas" or \
       x=="Omnicom":            
        return 'BIGHOLD'
    elif x=="Independent":        
        return 'INDY'
    else:        
        return 'SMALLHOLD'

In [11]:
adage = adage[['PARENT','2015 US REVENUE']]
adage.PARENT = adage.PARENT.apply(typer)
adage

        PARENT  2015 US REVENUE
0    SMALLHOLD          1855045
1    SMALLHOLD          1231596
2    SMALLHOLD           865200
3    SMALLHOLD           796800
4         INDY           765299
5      BIGHOLD           651665
6    SMALLHOLD           624000
7      BIGHOLD           602798
8      BIGHOLD           585000
9      BIGHOLD           561860
10   SMALLHOLD           523065
11     BIGHOLD           504176
12     BIGHOLD           489369
13     BIGHOLD           487887
14   SMALLHOLD           480668
15        INDY           464500
16     BIGHOLD           458754
17     BIGHOLD           458040
18     BIGHOLD           454575
19     BIGHOLD           448691
20   SMALLHOLD           432000
21     BIGHOLD           415743
22        INDY           380940
23     BIGHOLD           361661
24     BIGHOLD           358600
25     BIGHOLD           350458
26     BIGHOLD           337838
27     BIGHOLD           336209
28     BIGHOLD           331731
29   SMALLHOLD           325844
..         ...              ...
885       INDY             1452
886       INDY             1436
887       INDY             1333
888       INDY             1260
889       INDY             1250
890       INDY             1200
891       INDY             1170
892       INDY             1100
893       INDY             1100
894       INDY             1088
895       INDY             1050
896       INDY             1049
897       INDY             1027
898       INDY             1006
899       INDY             1000
900       INDY             1000
901  SMALLHOLD             1000
902       INDY             1000
903       INDY              964
904       INDY              908
905       INDY              865
906       INDY              853
907       INDY              761
908       INDY              585
909       INDY              510
910       INDY              495
911       INDY              450
912       INDY              375
913       INDY              333
914       INDY              104

[915 rows x 2 columns]

Let's understand more about that Group object

In [12]:
breakdown = adage.groupby('PARENT')
breakdown.sum()

           2015 US REVENUE
PARENT
BIGHOLD           22858077
INDY              12696425
SMALLHOLD         11198654

In [16]:
labels = [i for i in breakdown.sum().index]
labels

['BIGHOLD', 'INDY', 'SMALLHOLD']

In [17]:
values = [j for j in breakdown.sum()["2015 US REVENUE"]]
values

[22858077, 12696425, 11198654]

In [18]:
trace = go.Pie(labels=labels,values=values)
py.iplot([trace])