In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("/home/jupyter/src/dataviz/podcastcount/2LMarketBasket.xlsx")

In [3]:
df.shape

(10931, 44)

In [4]:
df.rename(columns = {'2L+ TKI Target':'2Lplus',
                     'LTD Reach - Live':'LiveRepTouch',
                     'LTD Reach - All Reach Methods':'AnyTouch',
                     'LTD QINLOCK Rx (HCP)' : 'WroteQinlock',
                     'April Marketing Campaign - Email Open Count':'AprilEmailOpens'},inplace = True)

In [5]:
list(df)

['NPI',
 'HCP ID',
 'First Name',
 'Last Name',
 'Specialty',
 'Sales Tier',
 'Facility Tier',
 '2Lplus',
 'AnyTouch',
 'LiveRepTouch',
 'AprilEmailOpens',
 'Total GIST Patients',
 'Total Treated GIST Patients',
 'Total 3L+ GIST Patients',
 'Total Ayva GIST Patients',
 'Komodo Clinical Experience Score',
 'Komodo Clinical Volume Score',
 'GLEEVEC Units - 52 Week',
 'GLEEVEC Units - 26 Week',
 'Sutent Units - 52 Week',
 'Sutent Units - 26 Week',
 'Stivarga Units - 52 Week',
 'Stivarga Units - 26 Week',
 'Ayva Units - 52 Week',
 'Ayva Units - 26 Week',
 'Other TKI Units - 52 Week',
 'Other TKI Units - 26 Week',
 '2L+ TKI Units - 52 Week',
 '2L+ TKI Units - 26 Week',
 'Field Reported 2L+',
 'WroteQinlock',
 'Region',
 'Territory',
 'Facility ID',
 'Facility Name',
 'Facility Address',
 'Facility Address 2',
 'Facility City',
 'Facility State',
 'Facility Zip',
 'Facility Phone',
 'Facility Fax',
 'Network/Parent',
 'Facility Segment']

In [6]:
pd.pivot_table(df,index=["2Lplus","Region"])

                    2L+ TKI Units - 26 Week  2L+ TKI Units - 52 Week  \
2Lplus Region
No     Central                     0.132107                 0.244147
       Great Lakes                 0.209841                 0.399421
       Northeast                   0.023739                 0.051929
       South                       0.161572                 0.269287
       Southeast                   0.082982                 0.205345
       West                        0.219638                 0.400517
Yes    Central                     2.041885                 3.921466
       Great Lakes                 2.004902                 4.004902
       Northeast                   2.657754                 4.791444
       South                       1.932990                 3.886598
       Southeast                   1.862559                 3.530806
       West                        1.322581                 2.562724

                    AnyTouch  AprilEmailOpens  Ayva Units - 26 Week  \
2Lplus Region
No     Central      1.774658         3.540000              0.005017
       Great Lakes  2.514036         3.204724              0.000000
       Northeast    1.439294         3.120846              0.000000
       South        2.276278         3.047210              0.000000
       Southeast    3.586261         3.040590              0.000000
       West         1.839329         3.388889              0.002584
Yes    Central      5.138393         3.181818              0.026178
       Great Lakes  6.476596         3.638298              0.014706
       Northeast    4.676190         2.808511              0.000000
       South        6.131455         3.409091              0.041237
       Southeast    8.902834         2.756098              0.052133
       West         4.927978         3.016129              0.050179

                    Ayva Units - 52 Week  Facility Zip  Field Reported 2L+  \
2Lplus Region
No     Central                  0.005017  64390.398630            0.000000
       Great Lakes              0.000000  34963.549595            0.000000
       Northeast                0.000000  10198.255519            0.000000
       South                    0.000000  70357.611506            0.000000
       Southeast                0.000000  31826.834819            0.000000
       West                     0.002584  92779.757794            0.000000
Yes    Central                  0.047120  60466.223214            1.489247
       Great Lakes              0.014706  34494.000000            1.656805
       Northeast                0.016043   9371.661905            1.333333
       South                    0.103093  71173.211268            1.356688
       Southeast                0.061611  31603.441296            1.241935
       West                     0.064516  93192.650970            1.484746

                    GLEEVEC Units - 26 Week  GLEEVEC Units - 52 Week  ...  \
2Lplus Region                                                         ...
No     Central                     2.070234                 4.133779  ...
       Great Lakes                 2.043415                 4.046310  ...
       Northeast                   2.243323                 4.379822  ...
       South                       2.314410                 4.499272  ...
       Southeast                   2.032349                 3.893108  ...
       West                        2.240310                 4.447028  ...
Yes    Central                     4.062827                 8.272251  ...
       Great Lakes                 5.171569                10.421569  ...
       Northeast                   6.759358                13.572193  ...
       South                       4.577320                 9.195876  ...
       Southeast                   5.199052                10.497630  ...
       West                        4.487455                 8.569892  ...

                    Other TKI Units - 26 Week  Other TKI Units - 52 Week  \
2Lplus Region
No     Central                       0.041806                   0.080268
       Great Lakes                   0.109986                   0.232996
       Northeast                     0.007418                   0.023739
       South                         0.055313                   0.109170
       Southeast                     0.032349                   0.108298
       West                          0.087855                   0.152455
Yes    Central                       0.696335                   1.413613
       Great Lakes                   0.848039                   1.622549
       Northeast                     0.871658                   1.631016
       South                         0.500000                   1.046392
       Southeast                     0.739336                   1.402844
       West                          0.444444                   0.896057

                    Stivarga Units - 26 Week  Stivarga Units - 52 Week  \
2Lplus Region
No     Central                      0.030100                  0.053512
       Great Lakes                  0.027496                  0.041968
       Northeast                    0.000000                  0.001484
       South                        0.011645                  0.023290
       Southeast                    0.002813                  0.004219
       West                         0.000000                  0.020672
Yes    Central                      0.345550                  0.617801
       Great Lakes                  0.279412                  0.460784
       Northeast                    0.401070                  0.748663
       South                        0.427835                  0.912371
       Southeast                    0.284360                  0.568720
       West                         0.146953                  0.265233

                    Sutent Units - 26 Week  Sutent Units - 52 Week  \
2Lplus Region
No     Central                    0.055184                0.105351
       Great Lakes                0.072359                0.124457
       Northeast                  0.016320                0.026706
       South                      0.094614                0.136827
       Southeast                  0.047820                0.092827
       West                       0.129199                0.224806
Yes    Central                    0.973822                1.842932
       Great Lakes                0.862745                1.906863
       Northeast                  1.385027                2.395722
       South                      0.963918                1.824742
       Southeast                  0.786730                1.497630
       West                       0.681004                1.336918

                    Total 3L+ GIST Patients  Total Ayva GIST Patients  \
2Lplus Region
No     Central                     1.000000                       1.0
       Great Lakes                 1.111111                       NaN
       Northeast                   1.000000                       NaN
       South                       1.000000                       NaN
       Southeast                   1.000000                       NaN
       West                        1.000000                       1.0
Yes    Central                     1.068966                       1.0
       Great Lakes                 1.128205                       1.0
       Northeast                   1.204545                       1.0
       South                       1.250000                       1.5
       Southeast                   1.113636                       1.0
       West                        1.030303                       1.0

                    Total GIST Patients  Total Treated GIST Patients
2Lplus Region
No     Central                 2.354515                     1.402685
       Great Lakes             2.515195                     1.421652
       Northeast               2.599407                     1.494048
       South                   2.847162                     1.540698
       Southeast               2.600563                     1.418605
       West                    2.064599                     1.434211
Yes    Central                 3.968586                     2.387500
       Great Lakes             5.171569                     2.565217
       Northeast               5.620321                     3.652695
       South                   4.231959                     2.596386
       Southeast               6.056872                     2.715026
       West                    3.820789                     2.351351

[12 rows x 23 columns]

In [7]:
pd.pivot_table(df,index=["2Lplus","Region"],values=["AprilEmailOpens"],aggfunc=[np.sum])

                               sum
                   AprilEmailOpens
2Lplus Region
No     Central               885.0
       Great Lakes           814.0
       Northeast            1033.0
       South                 710.0
       Southeast             824.0
       West                  671.0
Yes    Central               140.0
       Great Lakes           171.0
       Northeast             132.0
       South                 150.0
       Southeast             113.0
       West                  187.0

In [8]:
pd.pivot_table(df,index=["2Lplus","Region"],values=["Total 3L+ GIST Patients","AprilEmailOpens"],aggfunc=[np.sum])

                               sum
                   AprilEmailOpens Total 3L+ GIST Patients
2Lplus Region
No     Central               885.0                     6.0
       Great Lakes           814.0                    10.0
       Northeast            1033.0                     1.0
       South                 710.0                     7.0
       Southeast             824.0                     9.0
       West                  671.0                     8.0
Yes    Central               140.0                    31.0
       Great Lakes           171.0                    44.0
       Northeast             132.0                    53.0
       South                 150.0                    45.0
       Southeast             113.0                    49.0
       West                  187.0                    34.0

In [9]:
pd.pivot_table(df,index=["2Lplus","Region"],
               values=["Total 3L+ GIST Patients","Total Treated GIST Patients"],
               aggfunc=[np.sum])

                                       sum
                   Total 3L+ GIST Patients Total Treated GIST Patients
2Lplus Region
No     Central                         6.0                       418.0
       Great Lakes                    10.0                       499.0
       Northeast                       1.0                       502.0
       South                           7.0                       530.0
       Southeast                       9.0                       488.0
       West                            8.0                       327.0
Yes    Central                        31.0                       382.0
       Great Lakes                    44.0                       472.0
       Northeast                      53.0                       610.0
       South                          45.0                       431.0
       Southeast                      49.0                       524.0
       West                           34.0                       522.0

In [10]:
df["2Lplus"].value_counts()

No     9441
Yes    1490
Name: 2Lplus, dtype: int64

+ (41) 3L Patients among 9441 HCPs **THAT ARE NOT** 2L plus
+ (256) 3L Patients among 1490 HCPs **THAT ARE** 2L plus

In [11]:
pd.pivot_table(df,index=["2Lplus"],
               values=["Total 3L+ GIST Patients"],
               columns=["Region"],
               aggfunc=[np.sum])

                           sum
       Total 3L+ GIST Patients
Region                 Central Great Lakes Northeast South Southeast  West
2Lplus
No                         6.0        10.0       1.0   7.0       9.0   8.0
Yes                       31.0        44.0      53.0  45.0      49.0  34.0

In [12]:
table = pd.pivot_table(df,index=["2Lplus","Region"],
               values=["Total 3L+ GIST Patients","Total Treated GIST Patients","LiveRepTouch","AnyTouch"],
               aggfunc=[np.sum])
table

                        sum                                       \
                   AnyTouch LiveRepTouch Total 3L+ GIST Patients
2Lplus Region
No     Central         2591          652                     6.0
       Great Lakes     4030          801                    10.0
       Northeast       2608          234                     1.0
       South           3205          492                     7.0
       Southeast       6839         1159                     9.0
       West            2301          544                     8.0
Yes    Central         1151          408                    31.0
       Great Lakes     1522          340                    44.0
       Northeast        982          159                    53.0
       South           1306          262                    45.0
       Southeast       2199          550                    49.0
       West            1779          477                    34.0


                   Total Treated GIST Patients
2Lplus Region
No     Central                           418.0
       Great Lakes                       499.0
       Northeast                         502.0
       South                             530.0
       Southeast                         488.0
       West                              327.0
Yes    Central                           382.0
       Great Lakes                       472.0
       Northeast                         610.0
       South                             431.0
       Southeast                         524.0
       West                              522.0

In [13]:
table = pd.pivot_table(df,index=["2Lplus","Region"],
               values=["Total 3L+ GIST Patients","LiveRepTouch","AnyTouch","AprilEmailOpens"],
               aggfunc=[np.sum])
table

                        sum                               \
                   AnyTouch AprilEmailOpens LiveRepTouch
2Lplus Region
No     Central         2591           885.0          652
       Great Lakes     4030           814.0          801
       Northeast       2608          1033.0          234
       South           3205           710.0          492
       Southeast       6839           824.0         1159
       West            2301           671.0          544
Yes    Central         1151           140.0          408
       Great Lakes     1522           171.0          340
       Northeast        982           132.0          159
       South           1306           150.0          262
       Southeast       2199           113.0          550
       West            1779           187.0          477


                   Total 3L+ GIST Patients
2Lplus Region
No     Central                         6.0
       Great Lakes                    10.0
       Northeast                       1.0
       South                           7.0
       Southeast                       9.0
       West                            8.0
Yes    Central                        31.0
       Great Lakes                    44.0
       Northeast                      53.0
       South                          45.0
       Southeast                      49.0
       West                           34.0

In [14]:
list(table)

[('sum', 'AnyTouch'),
 ('sum', 'AprilEmailOpens'),
 ('sum', 'LiveRepTouch'),
 ('sum', 'Total 3L+ GIST Patients')]

In [15]:
table

                        sum                               \
                   AnyTouch AprilEmailOpens LiveRepTouch
2Lplus Region
No     Central         2591           885.0          652
       Great Lakes     4030           814.0          801
       Northeast       2608          1033.0          234
       South           3205           710.0          492
       Southeast       6839           824.0         1159
       West            2301           671.0          544
Yes    Central         1151           140.0          408
       Great Lakes     1522           171.0          340
       Northeast        982           132.0          159
       South           1306           150.0          262
       Southeast       2199           113.0          550
       West            1779           187.0          477


                   Total 3L+ GIST Patients
2Lplus Region
No     Central                         6.0
       Great Lakes                    10.0
       Northeast                       1.0
       South                           7.0
       Southeast                       9.0
       West                            8.0
Yes    Central                        31.0
       Great Lakes                    44.0
       Northeast                      53.0
       South                          45.0
       Southeast                      49.0
       West                           34.0

In [16]:
settings = pd.pivot_table(df,index=["2Lplus","Region"],
                values=["Total 3L+ GIST Patients"],
                columns=["Facility Segment"],
                aggfunc=[len])
settings

                                       len                                 \
                   Total 3L+ GIST Patients
Facility Segment                  AMC Flag IDN Flag Independent Hospitals
2Lplus Region
No     Central                       271.0    802.0                  31.0
       Great Lakes                   414.0    785.0                  39.0
       Northeast                     753.0    750.0                  55.0
       South                         250.0    663.0                  35.0
       Southeast                     313.0    803.0                  68.0
       West                          265.0    548.0                  87.0
Yes    Central                        57.0    104.0                   7.0
       Great Lakes                    57.0    111.0                   4.0
       Northeast                     114.0     65.0                   6.0
       South                          44.0     98.0                   7.0
       Southeast                      49.0    101.0                   9.0
       West                           76.0    160.0                  23.0



Facility Segment   Physician Group Practice
2Lplus Region
No     Central                        282.0
       Great Lakes                    216.0
       Northeast                      210.0
       South                          390.0
       Southeast                      552.0
       West                           228.0
Yes    Central                         49.0
       Great Lakes                     44.0
       Northeast                       19.0
       South                           47.0
       Southeast                       66.0
       West                            78.0

In [17]:
secondlineplus = df[df["2Lplus"] == "Yes"]
secondlineplus.shape

(1490, 44)

In [18]:
scripts = pd.pivot_table(secondlineplus,index=["WroteQinlock","Region"],
                values=["Total 3L+ GIST Patients"],
                columns=["Facility Segment"],                         
                aggfunc=[len])
scripts

                                             len           \
                         Total 3L+ GIST Patients
Facility Segment                        AMC Flag IDN Flag
WroteQinlock Region
No           Central                        34.0     77.0
             Great Lakes                    33.0     91.0
             Northeast                      65.0     57.0
             South                          26.0     82.0
             Southeast                      30.0     79.0
             West                           59.0    129.0
Yes          Central                        23.0     27.0
             Great Lakes                    24.0     20.0
             Northeast                      49.0      8.0
             South                          18.0     16.0
             Southeast                      19.0     22.0
             West                           17.0     31.0



Facility Segment         Independent Hospitals Physician Group Practice
WroteQinlock Region
No           Central                       6.0                     40.0
             Great Lakes                   2.0                     33.0
             Northeast                     5.0                     13.0
             South                         6.0                     36.0
             Southeast                     5.0                     50.0
             West                         19.0                     71.0
Yes          Central                       1.0                      9.0
             Great Lakes                   2.0                     11.0
             Northeast                     1.0                      6.0
             South                         1.0                     11.0
             Southeast                     4.0                     16.0
             West                          4.0                      7.0

In [43]:
thirdLnoQ = df[(df["2Lplus"] == "Yes")
    & (df["Total 3L+ GIST Patients"] > 0)
    & (df["WroteQinlock"]=="No")]
thirdLnoQ.shape

(132, 44)

In [44]:
thirdLsettings = pd.pivot_table(thirdLnoQ,index=["Region"],
                values=["Total 3L+ GIST Patients"],
                columns=["Facility Segment"],                         
                aggfunc=[len])
thirdLsettings

                                     len                                 \
                 Total 3L+ GIST Patients
Facility Segment                AMC Flag IDN Flag Independent Hospitals
Region
Central                              2.0     10.0                   NaN
Great Lakes                          6.0     13.0                   NaN
Northeast                           12.0     12.0                   1.0
South                                3.0      9.0                   1.0
Southeast                            5.0     16.0                   NaN
West                                 4.0      5.0                   2.0



Facility Segment Physician Group Practice
Region
Central                               2.0
Great Lakes                           3.0
Northeast                             1.0
South                                 3.0
Southeast                             6.0
West                                 10.0

In [45]:
thirdLnoQidn = df[(df["2Lplus"] == "Yes")
    & (df["Total 3L+ GIST Patients"] > 0)
    & (df["WroteQinlock"]=="No")
    & (df["Facility Segment"]=="IDN Flag")]
thirdLnoQidn.shape

SyntaxError: invalid syntax (<ipython-input-45-48144a6b3a7c>, line 1)

In [39]:
thirdLnoQidn

,NPI,HCP ID,First Name,Last Name,Specialty,Sales Tier,Facility Tier,2Lplus,AnyTouch,LiveRepTouch,...,Facility Name,Facility Address,Facility Address 2,Facility City,Facility State,Facility Zip,Facility Phone,Facility Fax,Network/Parent,Facility Segment
72,1528234143,DA01003353,SETH,POLLACK,HEMATOLOGY & ONCOLOGY,TIER 2,TIER 1,No,4,1,...,Northwestern Memorial Hospital,251 E HURON ST,NaN,CHICAGO,IL,60611,(312) 926-2520,(312) 926-6374,NaN,IDN Flag
81,1740228857,DA01007552,SAMIR,UNDEVIA,HEMATOLOGY & ONCOLOGY,TIER 2,TIER 2,No,6,1,...,Edward Hospital,801 S WASHINGTON ST,NaN,NAPERVILLE,IL,60540,(630) 355-0450,(630) 868-2240,NaN,IDN Flag
707,1568453298,DA01010233,MALIK,BANDEALY,HEMATOLOGY & ONCOLOGY,TIER 3,TIER 3,Yes,9,2,...,Aurora Cancer Care - Kenosha,6811 118TH AVE,NaN,KENOSHA,WI,53142,(262) 857-5700,(262) 857-1142,AURORA HEALTH CARE INC,IDN Flag
710,1497189468,DA01010234,ALLISON,HARDIN,HEMATOLOGY & ONCOLOGY,TIER 3,TIER 3,Yes,8,1,...,Aurora Cancer Care - Kenosha,6811 118TH AVE,NaN,KENOSHA,WI,53142,(262) 857-5700,(262) 857-1142,AURORA HEALTH CARE INC,IDN Flag
711,1588655351,DA01001549,KELLY,KONESKO,NURSE PRACTITIONER,TIER 3,TIER 2,Yes,12,4,...,Aurora Cancer Care - Racine,8400 WASHINGTON AVE,NaN,MOUNT PLEASANT,WI,53406,(262) 884-8340,(262) 884-8341,NaN,IDN Flag
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9820,1235101437,DA01000173,GARY,SHI,"ONCOLOGY, MEDICAL",TIER 2,TIER 2,Yes,9,3,...,Sutter Amador Hospital,200 MISSION BLVD,NaN,JACKSON,CA,95642,(209) 223-7500,(209) 223-7509,SUTTER HEALTH,IDN Flag
10362,1508889338,DA01001859,JARED,ACOBA,HEMATOLOGY & ONCOLOGY,TIER 1,TIER 1,Yes,8,2,...,Queens Medical Center,1301 PUNCHBOWL ST,NaN,HONOLULU,HI,96813,(808) 538-9011,(808) 537-7887,"""QUEEN'S HEALTH SYSTEMS""",IDN Flag
10421,1508833971,DA01001158,MELVIN,PALALAY,HEMATOLOGY & ONCOLOGY,TIER 1,TIER 1,No,12,4,...,Queens Medical Center,1301 PUNCHBOWL ST,NaN,HONOLULU,HI,96813,(808) 538-9011,(808) 537-7887,"""QUEEN'S HEALTH SYSTEMS""",IDN Flag
10602,1265610752,DA01003444,JORGE,CHAVES,HEMATOLOGY & ONCOLOGY,TIER 2,TIER 1,Yes,14,3,...,St Joseph Medical Center,1717 S J ST,NaN,TACOMA,WA,98405,(253) 627-4101,(253) 426-6880,CATHOLIC HEALTH INITIATIVES,IDN Flag
10610,1861587339,DA01003394,KAREN,HUNT,HEMATOLOGY & ONCOLOGY,TIER 2,TIER 2,Yes,8,0,...,Kalispell Regional Medical Center,310 SUNNYVIEW LN,NaN,KALISPELL,MT,59901,(406) 752-5111,(406) 756-3528,KALISPELL REGIONAL HEALTHCARE,IDN Flag

In [35]:
idnOpportunity = pd.pivot_table(thirdLnoQidn,index=["Network/Parent"],
                values=["Total 3L+ GIST Patients"],
                columns=["Region"],                        
                aggfunc=[len],fill_value=0)
idnOpportunity
#idnOpportunity.to_csv("/home/jupyter/src/dataviz/podcastcount/idnOpportunity.csv")

                                                                       len  \
                                                   Total 3L+ GIST Patients
Region                                                             Central
Network/Parent
"QUEEN'S HEALTH SYSTEMS"                                                 0
"SAINT JOSEPH'S CANDLER HEALTH SYSTEM"                                   0
ALBERT EINSTEIN HEALTHCARE NETWORK                                       0
ALLEGHENY HEALTH NETWORK                                                 0
ASCENSION HEALTH                                                         0
AURORA HEALTH CARE INC                                                   2
BETH ISRAEL HEALTHCARE                                                   0
CANCER TREATMENT CENTERS OF AMERICA                                      0
CARLE FOUNDATION                                                         2
CAROLINAS HEALTHCARE SYSTEM                                              0
CATHOLIC HEALTH INITIATIVES                                              0
CATHOLIC HEALTH SERVICES OF LONG ISLAND                                  0
COMMUNITY HEALTH SYSTEMS INC                                             0
COOPER HEALTH SYSTEM                                                     0
COXHEALTH                                                                1
DCH HEALTH SYSTEM                                                        0
DIGNITY HEALTH                                                           0
HCA HOLDINGS INC                                                         0
HOSPITAL SISTERS HEALTH SYSTEM                                           2
HOUSTON METHODIST                                                        0
HUNTSVILLE HOSPITAL HEALTH SYSTEM                                        0
IASIS HEALTHCARE LLC                                                     0
KALISPELL REGIONAL HEALTHCARE                                            0
LEXINGTON MEDICAL CENTER SYSTEM                                          0
LIFEPOINT HOSPITALS INC                                                  0
MEMORIAL HERMANN HEALTHCARE SYSTEM                                       0
MERCY (FORMERLY SISTERS OF MERCY)                                        1
MERCY HEALTH MINISTRY SUPPORT SERVICES (FORMERL...                       0
MERCY HEALTH NETWORK                                                     1
MIDDLESEX HEALTH SYSTEM                                                  0
NORTH SHORE-LONG ISLAND JEWISH HEALTH SYSTEM                             0
NORTHSIDE HOSPITAL HEALTHCARE SYSTEM                                     0
ROCHESTER REGIONAL HEALTH SYSTEM (AKA VIAHEALTH)                         0
SAINT TAMMANY PARISH HOSPITAL (SYSTEM)                                   0
STORMONT-VAIL HEALTHCARE                                                 1
SUMMA HEALTH SYSTEM                                                      0
SUTTER HEALTH                                                            0
TENET HEALTHCARE CORPORATION                                             0
TEXAS HEALTH RESOURCES                                                   0
UNIVERSAL HEALTH SERVICES                                                0
UNIVERSITY HEALTH CARE SYSTEM                                            0
WELLSTAR HEALTH SYSTEM                                                   0
WEST VIRGINIA UNITED HEALTH SYSTEM                                       0

                                                                          \

Region                                             Great Lakes Northeast
Network/Parent
"QUEEN'S HEALTH SYSTEMS"                                     0         0
"SAINT JOSEPH'S CANDLER HEALTH SYSTEM"                       0         0
ALBERT EINSTEIN HEALTHCARE NETWORK                           0         1
ALLEGHENY HEALTH NETWORK                                     1         0
ASCENSION HEALTH                                             0         0
AURORA HEALTH CARE INC                                       0         0
BETH ISRAEL HEALTHCARE                                       0         2
CANCER TREATMENT CENTERS OF AMERICA                          0         0
CARLE FOUNDATION                                             0         0
CAROLINAS HEALTHCARE SYSTEM                                  0         0
CATHOLIC HEALTH INITIATIVES                                  0         0
CATHOLIC HEALTH SERVICES OF LONG ISLAND                      0         1
COMMUNITY HEALTH SYSTEMS INC                                 0         0
COOPER HEALTH SYSTEM                                         0         1
COXHEALTH                                                    0         0
DCH HEALTH SYSTEM                                            0         0
DIGNITY HEALTH                                               0         0
HCA HOLDINGS INC                                             0         0
HOSPITAL SISTERS HEALTH SYSTEM                               0         0
HOUSTON METHODIST                                            0         0
HUNTSVILLE HOSPITAL HEALTH SYSTEM                            0         0
IASIS HEALTHCARE LLC                                         0         0
KALISPELL REGIONAL HEALTHCARE                                0         0
LEXINGTON MEDICAL CENTER SYSTEM                              0         0
LIFEPOINT HOSPITALS INC                                      1         0
MEMORIAL HERMANN HEALTHCARE SYSTEM                           0         0
MERCY (FORMERLY SISTERS OF MERCY)                            0         0
MERCY HEALTH MINISTRY SUPPORT SERVICES (FORMERL...           1         0
MERCY HEALTH NETWORK                                         0         0
MIDDLESEX HEALTH SYSTEM                                      0         1
NORTH SHORE-LONG ISLAND JEWISH HEALTH SYSTEM                 0         2
NORTHSIDE HOSPITAL HEALTHCARE SYSTEM                         0         0
ROCHESTER REGIONAL HEALTH SYSTEM (AKA VIAHEALTH)             0         2
SAINT TAMMANY PARISH HOSPITAL (SYSTEM)                       0         0
STORMONT-VAIL HEALTHCARE                                     0         0
SUMMA HEALTH SYSTEM                                          1         0
SUTTER HEALTH                                                0         0
TENET HEALTHCARE CORPORATION                                 0         0
TEXAS HEALTH RESOURCES                                       0         0
UNIVERSAL HEALTH SERVICES                                    1         0
UNIVERSITY HEALTH CARE SYSTEM                                0         0
WELLSTAR HEALTH SYSTEM                                       0         0
WEST VIRGINIA UNITED HEALTH SYSTEM                           1         0



Region                                             South Southeast West
Network/Parent
"QUEEN'S HEALTH SYSTEMS"                               0         0    2
"SAINT JOSEPH'S CANDLER HEALTH SYSTEM"                 0         1    0
ALBERT EINSTEIN HEALTHCARE NETWORK                     0         0    0
ALLEGHENY HEALTH NETWORK                               0         0    0
ASCENSION HEALTH                                       1         2    0
AURORA HEALTH CARE INC                                 0         0    0
BETH ISRAEL HEALTHCARE                                 0         0    0
CANCER TREATMENT CENTERS OF AMERICA                    0         1    0
CARLE FOUNDATION                                       0         0    0
CAROLINAS HEALTHCARE SYSTEM                            0         1    0
CATHOLIC HEALTH INITIATIVES                            0         0    1
CATHOLIC HEALTH SERVICES OF LONG ISLAND                0         0    0
COMMUNITY HEALTH SYSTEMS INC                           0         1    0
COOPER HEALTH SYSTEM                                   0         0    0
COXHEALTH                                              0         0    0
DCH HEALTH SYSTEM                                      0         2    0
DIGNITY HEALTH                                         1         0    0
HCA HOLDINGS INC                                       1         0    0
HOSPITAL SISTERS HEALTH SYSTEM                         0         0    0
HOUSTON METHODIST                                      1         0    0
HUNTSVILLE HOSPITAL HEALTH SYSTEM                      0         3    0
IASIS HEALTHCARE LLC                                   1         0    0
KALISPELL REGIONAL HEALTHCARE                          0         0    1
LEXINGTON MEDICAL CENTER SYSTEM                        0         1    0
LIFEPOINT HOSPITALS INC                                0         0    0
MEMORIAL HERMANN HEALTHCARE SYSTEM                     2         0    0
MERCY (FORMERLY SISTERS OF MERCY)                      0         0    0
MERCY HEALTH MINISTRY SUPPORT SERVICES (FORMERL...     0         0    0
MERCY HEALTH NETWORK                                   0         0    0
MIDDLESEX HEALTH SYSTEM                                0         0    0
NORTH SHORE-LONG ISLAND JEWISH HEALTH SYSTEM           0         0    0
NORTHSIDE HOSPITAL HEALTHCARE SYSTEM                   0         2    0
ROCHESTER REGIONAL HEALTH SYSTEM (AKA VIAHEALTH)       0         0    0
SAINT TAMMANY PARISH HOSPITAL (SYSTEM)                 1         0    0
STORMONT-VAIL HEALTHCARE                               0         0    0
SUMMA HEALTH SYSTEM                                    0         0    0
SUTTER HEALTH                                          0         0    2
TENET HEALTHCARE CORPORATION                           1         1    0
TEXAS HEALTH RESOURCES                                 3         0    0
UNIVERSAL HEALTH SERVICES                              1         0    0
UNIVERSITY HEALTH CARE SYSTEM                          0         1    0
WELLSTAR HEALTH SYSTEM                                 0         1    0
WEST VIRGINIA UNITED HEALTH SYSTEM                     0         0    0