In [1]:
import ijson
import pandas as pd

In [4]:
filename = "json_data/inc5000_2016.json"

In [5]:
good_columns = [
    "city",
    "state_l",
    "metro",
    "revenue",
    "url",
    "industry",
    "workers",
    "rank",
    "id",
    "yrs_on_list",
    "growth",
    "ifmid",
    "ifiid",
    "state_s",
    "company"
]

In [6]:
data16 = []
with open(filename, 'r') as f:
    for item in ijson.items(f, "item"):
        data16.append(item.values())

In [7]:
data16[299]

[u'White Plains',
 u'New York',
 u'New York City',
 5758886,
 u'licenselogix',
 u'Business Products & Services',
 32,
 300,
 43175,
 1,
 Decimal('1300.32'),
 9,
 17,
 u'NY',
 u'LicenseLogix']

In [9]:
df = pd.DataFrame(data16, columns = good_columns)

In [10]:
df

,city,state_l,metro,revenue,url,industry,workers,rank,id,yrs_on_list,growth,ifmid,ifiid,state_s,company
0,Los Angeles,California,Los Angeles,116247698,loot-crate,Consumer Products & Services,218,1,42940,1,66788.5962,2,4,CA,Loot Crate
1,Somerville,Massachusetts,Boston,55018793,paint-nite,Consumer Products & Services,100,2,42941,1,36555.2472,6,4,MA,Paint Nite
2,Visalia,California,"Visalia-Porterville, CA",33507450,calcom-solar,Energy,47,3,42942,1,31633.5448,172,16,CA,CalCom Solar
3,Evansville,Indiana,"Evansville, IN-KY",30695215,eluxurysupplycom,Retail,82,4,36643,2,23619.7198,641,18,IN,eLuxurySupply.com
4,Atlanta,Georgia,Atlanta,33370967,companycom,Business Products & Services,48,5,36639,2,23486.8894,29,17,GA,Company.com
5,Cambridge,Massachusetts,Boston,17743829,globalization-partners,Business Products & Services,15,6,42943,1,16196.5338,6,17,MA,Globalization Partners
6,New York,New York,New York City,15733570,bounce-exchange,Software,130,7,42944,1,14574.6474,9,9,NY,Bounce Exchange
7,Santa Monica,California,Los Angeles,15598837,los-york,Advertising & Marketing,25,8,42945,1,14404.6093,2,5,CA,Los York
8,Pittsburgh,Pennsylvania,"Pittsburgh, PA",42425003,pantherx-specialty-pharmacy,Health,39,9,42946,1,13380.8799,52,10,PA,PANTHERx Specialty Pharmacy
9,Leesburg,Virginia,"Washington, DC",25863238,fedbiz-it-solutions,Government Services,9,10,42947,1,12620.5845,3,7,VA,FedBiz IT Solutions
10,Columbus,Ohio,"Columbus, OH",12369863,small-business-owners-of-america,Financial Services,14,11,42948,1,12059.8622,19,2,OH,Small Business Owners of America
11,Charlotte,North Carolina,Charlotte,11518066,planit-group,IT Services,52,12,42949,1,11525.3681,43,8,NC,PLANIT GROUP
12,San Diego,California,San Diego,65877327,suja-juice,Food & Beverage,250,13,42950,1,10511.0846,11,11,CA,Suja Juice
13,Addison,Texas,Dallas,28804779,s2-capital,Real Estate,105,14,42951,1,9645.7324,8,3,TX,S2 Capital
14,Grand Rapids,Michigan,"Grand Rapids-Wyoming, MI",11212596,formulafolio-investments,Financial Services,35,15,37197,2,9400.5092,219,2,MI,FormulaFolio Investments
15,New York,New York,New York City,17432811,persado,Software,171,16,42952,1,9389.7747,9,9,NY,Persado
16,Carson,California,Los Angeles,11449478,berkley,Manufacturing,15,17,42953,1,9249.2602,2,15,CA,Berkley
17,New York,New York,New York City,14917600,exusia,IT Services,185,18,42954,1,8803.2659,9,8,NY,Exusia
18,Roswell,Georgia,Atlanta,23181949,thrive-farmers,Food & Beverage,35,19,42955,1,8577.1781,29,11,GA,Thrive Farmers
19,Hollywood,Florida,Miami,8629685,tribeca-marketing-group,Education,10,20,42956,1,8395.2895,1,19,FL,Tribeca Marketing Group
20,Westchester,Illinois,Chicago,17349869,ch-financial-services,Financial Services,15,21,36809,2,8052.9041,17,2,IL,C&H Financial Services
21,Apollo Beach,Florida,Tampa,8099089,paykings,Financial Services,6,22,42957,1,7905.4255,7,2,FL,PAYKINGS
22,Londonderry,New Hampshire,Boston,8003634,highland-project-logistics,Logistics & Transportation,5,23,42958,1,7903.554,6,6,NH,Highland Project Logistics
23,Annapolis,Maryland,Baltimore,8623201,furniture-solutions-group,Business Products & Services,8,24,42959,1,7799.5978,35,17,MD,Furniture Solutions Group
24,Oakbrook,Illinois,Chicago,971148423,midwest-equity-mortgage,Financial Services,200,25,37267,2,7754.3956,17,2,IL,Midwest Equity Mortgage
25,San Diego,California,San Diego,19031027,big-block-realty,Real Estate,16,26,42960,1,7612.7068,11,3,CA,Big Block Realty
26,Irvine,California,Los Angeles,11100000,cylance,Security,235,26,44578,1,7613.0469,2,13,CA,Cylance
27,Boca Raton,Florida,Miami,9718979,blackstone-labs,Health,30,27,42961,1,7546.0566,1,10,FL,Blackstone Labs
28,Chicago,Illinois,Chicago,18557648,elements-holdings-group-inc-subsidiaries,Business Products & Services,25,28,42962,1,7117.1678,17,17,IL,Elements Holdings Group Inc & Subsidiaries
29,Washington,Utah,"St. George, UT",13005808,legend-solar,Energy,140,29,42963,1,7101.8827,308,16,UT,Legend Solar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4973,Chino,California,"Riverside-San Bernardino-Ontario, CA",125672898,nexgrill-industries,Consumer Products & Services,57,4971,44569,1,41.1087,54,4,CA,Nexgrill Industries
4974,Irving,Texas,Dallas,17900000,us-analytics-solutions-group,Business Products & Services,72,4972,24399,4,41.0782,8,17,TX,US-Analytics Solutions Group
4975,MARIETTA,Georgia,Atlanta,41548751,saturn-freight-systems,Logistics & Transportation,131,4973,3932,7,40.9159,29,6,GA,Saturn Freight Systems
4976,N Lakewood,Washington,Seattle,75574615,central-welding-supply,Business Products & Services,250,4974,18517,3,40.8664,23,17,WA,Central Welding Supply
4977,Cranberry Township,Pennsylvania,"Pittsburgh, PA",529623000,pls-logistics-services,Logistics & Transportation,553,4975,4025,3,40.7902,52,6,PA,PLS Logistics Services
4978,New York,New York,New York City,7208754,klingman-associates,Financial Services,13,4976,44570,1,40.7156,9,2,NY,Klingman & Associates
4979,New Orleans,Louisiana,"New Orleans-Metairie, LA",12000809,civicsource,Government Services,54,4977,44571,1,40.7194,1010,7,LA,CivicSource
4980,South Jordan,Utah,Salt Lake City,2930244,3-key-elements,Education,25,4978,23072,4,40.708,12,19,UT,3 Key Elements
4981,Louisville,Kentucky,"Louisville/Jefferson County, KY-IN",20042109,justice-av-solutions,Manufacturing,121,4979,44572,1,40.71,630,15,KY,Justice AV Solutions
4982,Richmond Heights,Ohio,Cleveland,50451607,omni-systems,Manufacturing,98,4980,3756,6,40.6613,79,15,OH,OMNI Systems
4983,Ann Arbor,Michigan,"Ann Arbor, MI",4656600,dynamic-edge,IT Services,54,4981,38185,2,40.6594,84,8,MI,Dynamic Edge
4984,Mahwah,New Jersey,New York City,8918190,cases-by-source,Manufacturing,21,4982,4180,6,40.6337,9,15,NJ,Cases By Source
4985,Denham Springs,Louisiana,"Baton Rouge, LA",2197996,darren-james-real-estate-experts,Real Estate,7,4983,37213,2,40.5998,139,3,LA,Darren James Real Estate Experts
4986,New York,New York,New York City,4105744,hawkins-international-public-relations,Travel & Hospitality,29,4984,25574,3,40.5837,9,22,NY,Hawkins International Public Relations
4987,Lansing,Michigan,"Lansing-East Lansing, MI",69603000,liquid-web,IT Services,481,4985,888,10,40.4646,144,8,MI,Liquid Web
4988,Princeton Junction,New Jersey,"Trenton, NJ",17851875,newagesys,IT Services,260,4986,11627,8,40.4367,1012,8,NJ,NewAgeSys
4989,Annandale,New Jersey,New York City,5309000,blue-ocean-pharma,Advertising & Marketing,26,4987,44573,1,40.4126,9,5,NJ,Blue Ocean Pharma
4990,Rochelle Park,New Jersey,New York City,3520611,tenaglia-hunt,Business Products & Services,30,4988,44574,1,40.3884,9,17,NJ,Tenaglia & Hunt
4991,Cookeville,Tennessee,"Cookeville, TN",5462004,lenny-eva,Consumer Products & Services,12,4989,44575,1,40.368,613,4,TN,Lenny & Eva
4992,Otsego,Minnesota,Minneapolis,58817000,accurate-home-care,Health,2323,4990,20473,6,40.2554,13,10,MN,Accurate Home Care
4993,Austin,Texas,Austin,14071111,digital-marketer,Advertising & Marketing,135,4991,44576,1,40.2551,18,5,TX,Digital Marketer
4994,Boston,Massachusetts,Boston,6807000,sperry-van-ness-international,Real Estate,9,4992,8160,3,40.206,6,3,MA,Sperry Van Ness International
4995,Nashville,Tennessee,Nashville,35373305,letterlogic,Business Products & Services,51,4993,1821,10,40.127,82,17,TN,LetterLogic
4996,Mountain View,California,San Jose,363500000,fenwick-west,Business Products & Services,303,4994,19049,5,40.0771,20,17,CA,Fenwick & West
4997,Lehi,Utah,"Provo-Orem, UT",10755433,stonehaven-dental,Health,104,4995,44577,1,40.076,48,10,UT,Stonehaven Dental
4998,Farmington Hills,Michigan,Detroit,15233132,duffey-petrosky,Advertising & Marketing,105,4996,4114,8,40.0476,50,5,MI,Duffey Petrosky
4999,Brookfield,Connecticut,"Bridgeport-Stamford-Norwalk, CT",3713531,southridge-technology-grp,IT Services,22,4997,20674,6,39.8074,58,8,CT,Southridge Technology Grp
5000,Fishers,Indiana,"Indianapolis, IN",102252325,stratosphere-quality,Manufacturing,1951,4998,23258,4,39.7451,81,15,IN,Stratosphere Quality
5001,Ontario,New York,"Rochester, NY",27989715,optimax-systems,Manufacturing,278,4999,9017,5,39.7253,71,15,NY,Optimax Systems
5002,Houston,Texas,Houston,5714518,murray-resources,Human Resources,277,5000,24552,3,39.7237,22,21,TX,Murray Resources