In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
insiders = pd.read_csv('./influencer-data/1200insiders.csv')
insiders.columns.values.tolist()

['Twitter Handle',
 'Twitter ID',
 'Full Name',
 'Person/Company',
 'Number of followers',
 'Number of friends',
 'Number of total tweets',
 'Description',
 'Location (raw)',
 'Profile Image URL',
 'Insider Score',
 'Listening',
 'Emergence Score',
 'Age of account (days)',
 'Tweets per day',
 'First Name',
 'Last Name',
 'Location (continent)',
 'Location (country)',
 'Location (region)',
 'Location (sub_region)',
 'Related Website',
 'Insider Blogs',
 'StackOverflow',
 'Instagram',
 'Pinterest',
 'YouTube',
 'Google+',
 'SlideShare',
 'LinkedIn',
 'Quora',
 'AngelList',
 'Facebook',
 'Community Id',
 'Community Name',
 'Facebook ID']

In [3]:
mostpopular = insiders["Profile Image URL"].tail(500)
mostpopular.to_csv('mostpopular-profile-pics_500.csv', index=False)

In [4]:
handles = insiders['Twitter Handle'].tail(1000)
# handles.tail()
handles.to_csv('mostpopular-handles_1000.csv', index=False)

In [14]:
influencers = insiders.groupby(['Number of followers','Number of total tweets']).sum()
influencers.tail()

,,Twitter ID,Number of friends,Insider Score,Listening,Emergence Score,Age of account (days),Tweets per day,Community Id,Community Name,Facebook ID
Number of followers,Number of total tweets,,,,,,,,,,
817815,36267,12480582,12185,71,3,0.025849,2758,13,3.0,NaN,NaN
848474,287,6844292,1,64,0,0.021579,2977,0,2.0,NaN,NaN
916805,34629,17193794,2582,57,18,0.023198,2468,14,3.0,NaN,NaN
1047178,66398,5763262,1261,176,14,0.058502,3020,21,3.0,NaN,NaN
1462124,22169,27860681,541,39,3,0.016873,2323,9,3.0,NaN,NaN