In [1]:
# Just a basic configuration
import pandas as pd

In [2]:
sixteen='./csv_data/2016_inc5k.csv'
fifteen='./csv_data/2015_inc5k.csv'
fourteen='./csv_data/2014_inc5k.csv'
thirteen='./csv_data/2013_inc5k.csv'
df16 = pd.read_csv(sixteen).rename(columns=str.lower)
df16['company'] = df16['company'].str.lower()
df16.name = 'df16'
df15 = pd.read_csv(fifteen).rename(columns=str.lower)
df15['company'] = df15['company'].str.lower()
df15.name = 'df15'
df14 = pd.read_csv(fourteen).rename(columns=str.lower)
df14['company'] = df14['company'].str.lower()
df14.name = 'df14'
df13 = pd.read_csv(thirteen).rename(columns=str.lower)
df13['company'] = df13['company'].str.lower()
df13.name = 'df13'
df13

,unnamed: 0,city,state_l,metro,revenue,url,industry,workers,rank,id,yrs_on_list,growth,ifmid,ifiid,state_s,company
0,0,El Segundo,California,Los Angeles,117872000,fuhu,Consumer Products & Services,143,1,22890,1,42148.0287,2,4,CA,fuhu
1,1,Dumfries,Virginia,"Washington, DC",49625829,federalconferencecom,Government Services,51,2,20989,2,24830.5869,3,7,VA,federalconference.com
2,2,Jacksonville,Florida,"Jacksonville, FL",25501186,the-hci-group,Health,113,3,22892,1,24544.7799,64,10,FL,the hci group
3,3,Carrollton,Texas,Dallas,1919062000,bridger,Energy,50,4,22893,1,23308.1822,8,16,TX,bridger
4,4,Boston,Massachusetts,Boston,87036000,dataxu,Advertising & Marketing,220,5,22894,1,21337.4384,6,5,MA,dataxu
5,5,Austin,Texas,Austin,45683484,milestone-community-builders,Real Estate,63,6,22895,1,17937.7485,18,3,TX,milestone community builders
6,6,Nashville,Tennessee,CBSA Metro Region,25489171,value-payment-systems,Financial Services,27,7,22896,1,17404.1348,977,2,TN,value payment systems
7,7,San Francisco,California,San Francisco,23858231,emerge-digital-group,Advertising & Marketing,75,8,22897,1,17064.0715,4,5,CA,emerge digital group
8,8,Bluffdale,Utah,Salt Lake City,33104308,goal-zero,Consumer Products & Services,97,9,22898,1,16980.5405,12,4,UT,goal zero
9,9,Warwick,Rhode Island,"Providence-New Bedford-Fall River, RI-MA",18636055,yagoozon,Retail,15,10,21148,2,16689.2387,55,18,RI,yagoozon
10,10,Vienna,Virginia,"Washington, DC",29616593,obxtek,Government Services,149,11,20997,2,16433.2059,3,7,VA,obxtek
11,11,San Francisco,California,San Francisco,34121000,adroll,Advertising & Marketing,200,12,20974,2,15064.8889,4,5,CA,adroll
12,12,Orlando,Florida,"Orlando, FL",17042525,ubreakifix,Retail,180,13,22899,1,14102.1042,68,18,FL,ubreakifix
13,13,Charleston,South Carolina,"Charleston-North Charleston, SC",21138888,sparc,Software,160,14,22900,1,12862.5195,536,9,SC,sparc
14,14,Washington,District of Columbia,"Washington, DC",536000000,livingsocial,Consumer Products & Services,4100,15,22901,1,12333.1688,3,4,DC,livingsocial
15,15,Chino,California,"Riverside-San Bernardino-Ontario, CA",14295000,amped-wireless,Computer Hardware,26,16,22902,1,11067.9688,54,25,CA,amped wireless
16,16,Sarasota,Florida,"Sarasota-Bradenton-Venice, FL",11076624,integrity-funding,Financial Services,11,18,20972,2,10462.1421,576,2,FL,integrity funding
17,17,Columbus,Ohio,"Columbus, OH",11775633,vertex-body-sciences,Food & Beverage,51,19,22904,1,10010.3562,19,11,OH,vertex body sciences
18,18,Cupertino,California,San Jose,26799334,bluekai,Advertising & Marketing,107,20,22905,1,9245.4970,20,5,CA,bluekai
19,19,Seattle,Washington,Seattle,9628535,level-11,IT Services,30,21,22906,1,9043.9079,23,8,WA,level 11
20,20,Austin,Texas,Austin,9770645,patient-conversation-media,Health,59,22,21096,2,8782.4045,18,10,TX,patient conversation media
21,21,Dallas,Texas,Dallas,76981000,wingspan-portfolio-advisors,Financial Services,1704,23,22821,1,8768.7788,8,2,TX,wingspan portfolio advisors
22,22,Portland,Maine,"Portland-South Portland, ME",14629177,vets-first-choice,Health,74,24,20992,2,8585.3030,1018,10,ME,vets first choice
23,23,Frisco,Texas,Dallas,13785928,timberhorn,IT Services,175,25,22858,1,8516.2050,8,8,TX,timberhorn
24,24,New York,New York,New York City,13740852,beenverified,Consumer Products & Services,17,26,22907,1,8442.6497,9,4,NY,beenverified
25,25,Boulder,Colorado,"Boulder, CO",12555504,trada,Advertising & Marketing,75,27,22908,1,8100.9053,31,5,CO,trada
26,26,Orlando,Florida,"Orlando, FL",51118355,kony,Software,1100,28,22909,1,7786.2497,68,9,FL,kony
27,27,Irving,Texas,Dallas,23478000,onesource-virtual,Business Products & Services,260,29,22910,1,7353.3333,8,17,TX,onesource virtual
28,28,New York,New York,New York City,8066424,sailthru,Advertising & Marketing,79,30,22911,1,7322.1789,9,5,NY,sailthru
29,29,Atlanta,Georgia,Atlanta,8039700,innovolt,Business Products & Services,30,31,22912,1,7247.6942,29,17,GA,innovolt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4945,4945,Southern Pines,North Carolina,"Southern Pines-Pinehurst, NC",61334413,trident-marketing,Advertising & Marketing,487,4972,2310,5,35.1518,152,5,NC,trident marketing
4946,4946,Taunton,Massachusetts,"Providence-New Bedford-Fall River, RI-MA",5209454,hs-brands-international,Business Products & Services,26,4973,20794,3,35.1349,55,17,MA,hs brands international
4947,4947,Tampa,Florida,Tampa,23581000,pilgrim-software,Software,126,4974,7262,5,35.0805,7,9,FL,pilgrim software
4948,4948,Oklahoma City,Oklahoma,"Oklahoma City, OK",4634455,impressions-printing,Manufacturing,49,4975,4258,6,35.0671,38,15,OK,impressions printing
4949,4949,Houston,Texas,Houston,45552039,datacert,Software,252,4976,6205,9,35.0285,22,9,TX,datacert
4950,4950,Tucson,Arizona,"Tucson, AZ",81601287,buffalo-exchange,Retail,756,4977,7455,6,34.9787,154,18,AZ,buffalo exchange
4951,4951,Burke,Virginia,"Washington, DC",8678866,sun-design-remodeling-specialists,Construction,52,4978,4122,4,34.9526,3,20,VA,sun design remodeling specialists
4952,4952,McLean,Virginia,"Washington, DC",25953273,trowbridge-trowbridge,Government Services,224,4979,19503,3,34.9108,3,7,VA,trowbridge & trowbridge
4953,4953,Winston-Salem,North Carolina,"Winston-Salem, NC",5109775,frank-myers-auto-maxx,Consumer Products & Services,35,4980,22430,2,34.9086,245,4,NC,frank myers auto maxx
4954,4954,Hauppauge,New York,New York City,57324295,smartsource-computer-audio-visual-rentals,Business Products & Services,296,4981,24586,1,34.8994,9,17,NY,smartsource computer & audio visual rentals
4955,4955,Lakewood,Colorado,Denver,4144441,hpc-solutions,Government Services,18,4982,21661,3,34.8780,30,7,CO,hpc solutions
4956,4956,Boston,Massachusetts,Boston,58707280,baystate-financial-services,Financial Services,335,4983,4199,5,34.8762,6,2,MA,baystate financial services
4957,4957,Rocklin,California,"Sacramento--Arden-Arcade--Roseville, CA",21044000,cell-marque,Health,72,4984,20373,3,34.8542,75,10,CA,cell marque
4958,4958,Mars,Pennsylvania,"Pittsburgh, PA",38409224,celtic-healthcare,Health,498,4985,24587,1,34.8385,52,10,PA,celtic healthcare
4959,4959,Tysons Corner,Virginia,"Washington, DC",19476572,neosystems,Financial Services,108,4986,18479,4,34.7837,3,2,VA,neosystems
4960,4960,Plano,Texas,Denver,42469720,temporary-housing-directory,Travel & Hospitality,50,4987,2371,6,34.7626,30,22,TX,temporary housing directory
4961,4961,Englewood,Colorado,Denver,21381632,red-book-solutions,Business Products & Services,105,4988,19194,2,34.7619,30,17,CO,red book solutions
4962,4962,Moraine,Ohio,"Dayton, OH",130744000,lastar,Manufacturing,511,4989,18661,4,34.7404,39,15,OH,lastar
4963,4963,Charleston,South Carolina,"Charleston-North Charleston, SC",8748231,urban-nirvana,Travel & Hospitality,220,4990,4132,4,34.6844,536,22,SC,urban nirvana
4964,4964,Livermore,California,San Francisco,10740186,cablewholesale,Computer Hardware,27,4991,24588,1,34.6595,4,25,CA,cablewholesale
4965,4965,Middleton,Massachusetts,Boston,7445497,salem-metal-fabricators,Manufacturing,50,4992,24589,1,34.6513,6,15,MA,salem metal fabricators
4966,4966,North Little Rock,Arkansas,"Little Rock-North Little Rock-Conway, AR",2019218,the-pi-company,Business Products & Services,6,4993,24590,1,34.6300,122,17,AR,the pi company
4967,4967,Downers Grove,Illinois,Chicago,7167015,rfb-holdings,Human Resources,27,4994,4266,4,34.5593,17,21,IL,rfb holdings
4968,4968,Dakota Dunes,South Dakota,"Sioux City, IA-NE-SD",166032779,sterling-computers,Government Services,98,4995,20270,3,34.5594,709,7,SD,sterling computers
4969,4969,Montvale,New Jersey,New York City,13445156,csubs,Business Products & Services,19,4996,1492,6,34.4437,9,17,NJ,csubs
4970,4970,Mt. Sterling,Illinois,Nashville,4527289905,dot-foods,Food & Beverage,3919,4997,24591,1,34.3834,82,11,IL,dot foods
4971,4971,Wellington,Florida,Miami,6813166,lethal-performance,Retail,8,4998,24592,1,34.3256,1,18,FL,lethal performance
4972,4972,Mebane,North Carolina,"Burlington, NC",32621742,arcatech-systems,Financial Services,63,4999,1197,6,34.2575,170,2,NC,arcatech systems
4973,4973,Kimberton,Pennsylvania,Philadelphia,4710000,all4,Environmental Services,34,5000,3829,6,34.2263,49,23,PA,all4
4974,4974,Bellevue,Washington,Seattle,6815293,ine,Education,35,5000,4,3,34.2289,23,19,WA,ine

In [3]:
eventmarketer='./csv_data/study-list.csv'
#eventmarketer='./csv_data/new-it-list.csv'
#eventmarketer='./csv_data/it-list.csv'
#eventmarketer='./csv_data/rewritten-itlist.csv'
emdf = pd.read_csv(eventmarketer).rename(columns=str.lower)
emdf['company'] = emdf['company'].str.lower()
emdf.name = 'emdf'
#emdf = pd.read_csv(eventmarketer)
emdf

,company,tags
0,activent marketing,all guerrilla-street-programs mobile-tours spo...
1,advantage international,all b-to-b-meetingsevents mobile-tours sponsor...
2,agencyea,all b-to-b-meetingsevents internal-employee-ev...
3,all terrain,all buzz-influencer-programs mobile-tours spon...
4,allied experiential,all mobile-tours pr-events pop-up-stores
5,astound group,all launch-events mobile-tours trade-shows
6,barkley kalpak agency,all b-to-b-meetingsevents launch-events sales-...
7,bmf media,all buzz-influencer-programs launch-events spo...
8,bolt marketing group,all guerrilla-street-programs mobile-tours spo...
9,bottlerocket marketing,all mobile-tours pr-events sampling
10,broadstreet,all b-to-b-meetingsevents internal-employee-ev...
11,c3 agency,all buzz-influencer-programs launch-events pop...
12,cardenas marketing network,all retailtainment-events multicultural-events...
13,cramer,all b-to-b-meetingsevents internal-employee-ev...
14,division black,all buzz-influencer-programs guerrilla-street-...
15,driveshop,all automotive-launches-and-personal-drive-exp...
16,elemento l2,all mobile-tours multicultural-events sponsors...
17,elite marketing group,all guerrilla-street-programs mobile-tours sam...
18,emg3,all mobile-tours sampling sponsorship-activation
19,engine shop,all buzz-influencer-programs mobile-tours spon...
20,epsilon,all b-to-b-meetingsevents mobile-tours nightli...
21,event strategy group,all b-to-b-meetingsevents launch-events worldw...
22,eventage,all b-to-b-meetingsevents launch-events pr-events
23,eventive,all mobile-tours sponsorship-activation trade-...
24,eventnext,all launch-events mobile-tours sampling
25,executive visions inc.,all b-to-b-meetingsevents launch-events worldw...
26,factory 360,all pop-up-stores sampling sponsorship-activation
27,fcbx,all buzz-influencer-programs pr-events sponsor...
28,first protocol,all b-to-b-meetingsevents internal-employee-ev...
29,fluent,all college-campus-marketing guerrilla-street-...
...,...,...
70,mosaic,all guerrilla-street-programs launch-events ni...
71,motive,all college-campus-marketing events-for-conten...
72,mvp collaborative,all b-to-b-meetingsevents sales-conferencesmee...
73,na collective,all b-to-b-meetingsevents launch-events press-...
74,ncompass,all retailtainment-events launch-events sponso...
75,newbridge live,all college-campus-marketing mobile-tours samp...
76,next marketing,all mobile-tours sampling sponsorship-activation
77,nve,all buzz-influencer-programs developer-confere...
78,octagon,all mobile-tours sponsorship-activation worldw...
79,on board experiential,all b-to-b-meetingsevents mobile-tours sponsor...
80,opus agency,all b-to-b-meetingsevents sponsorship-activati...
81,performance marketing group,all b-to-b-meetingsevents sampling sponsorship...
82,pgw experience,all guerrilla-street-programs mobile-tours spo...
83,pop2life,all launch-events pr-events sponsorship-activa...
84,proscenium,all b-to-b-meetingsevents internal-employee-ev...
85,redpeg marketing,all mobile-tours sampling sponsorship-activation
86,revel,all b-to-b-meetingsevents buzz-influencer-prog...
87,revolution,all mobile-tours sponsorship-activation sports...
88,set,all retailtainment-events launch-events pop-up...
89,soho experiential,all buzz-influencer-programs mobile-tours nigh...
90,sparks,all b-to-b-meetingsevents developer-conference...
91,superfly,all buzz-influencer-programs sponsorship-activ...
92,switch,all b-to-b-meetingsevents mobile-tours sponsor...
93,synergy,all mobile-tours pr-events sponsorship-activation
94,the taylor group,all b-to-b-meetingsevents developer-conference...
95,touch worldwide,all b-to-b-meetingsevents internal-employee-ev...
96,track marketing group,all buzz-influencer-programs pr-events sponsor...
97,united entertainment group,all retailtainment-events launch-events pr-events
98,the visionary group,all b-to-b-meetingsevents buzz-influencer-prog...
99,wasserman,all pr-events sponsorship-activation worldwide...

In [4]:
# affordable
radar16 = df16[(df16['revenue'].astype('int') > 999999) & (df16['revenue'].astype('int') < 39999999)]
radar15 = df15[(df15['revenue'].astype('int') > 999999) & (df15['revenue'].astype('int') < 39999999)]
radar14 = df14[(df14['revenue'].astype('int') > 999999) & (df14['revenue'].astype('int') < 39999999)]
radar13 = df13[(df13['revenue'].astype('int') > 999999) & (df13['revenue'].astype('int') < 39999999)]

In [5]:
# advertising and marketing
agencies16 = radar16[(radar16['industry'] == "Advertising & Marketing")]
agencies15 = radar15[(radar15['industry'] == "Advertising & Marketing")]
agencies14 = radar14[(radar14['industry'] == "Advertising & Marketing")]
agencies13 = radar13[(radar13['industry'] == "Advertising & Marketing")]

- - -
> Ok—there are more in the metro of SF than in the city, so let's start there...

In [6]:
# in California
bayarea16 = agencies16[(agencies16['metro'] == "San Francisco")]
bayarea15 = agencies15[(agencies15['metro'] == "San Francisco")]
bayarea14 = agencies14[(agencies14['metro'] == "San Francisco")]
bayarea13 = agencies13[(agencies13['metro'] == "San Francisco")]

In [7]:
# in California
tristate16 = agencies16[(agencies16['metro'] == "New York City")]
tristate15 = agencies15[(agencies15['metro'] == "New York City")]
tristate14 = agencies14[(agencies14['metro'] == "New York City")]
tristate13 = agencies13[(agencies13['metro'] == "New York City")]

In [8]:
ind = bayarea16.company.isin(emdf.company)
ind

291     False
539     False
716     False
900     False
1114    False
1493    False
1588    False
1703    False
1769    False
2183    False
2867    False
3088    False
3103    False
3183     True
4003    False
4012    False
4054    False
Name: company, dtype: bool

In [9]:
bayarea16.shape

(17, 16)

In [10]:
bayarea16.isin(['manifold'])

,unnamed: 0,city,state_l,metro,revenue,url,industry,workers,rank,id,yrs_on_list,growth,ifmid,ifiid,state_s,company
291,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
539,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
716,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
900,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1114,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1493,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1588,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1703,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1769,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2183,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2867,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3088,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3103,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3183,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
4003,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4012,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4054,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
bayarea16[bayarea16['company']=='manifold']

,unnamed: 0,city,state_l,metro,revenue,url,industry,workers,rank,id,yrs_on_list,growth,ifmid,ifiid,state_s,company
3183,3183,San Francisco,California,San Francisco,14863448,manifold,Advertising & Marketing,16,3183,44172,1,105.7138,4,5,CA,manifold

In [12]:
emdf[emdf['company']=='manifold']

     company                                               tags
58  manifold  all buzz-influencer-programs developer-confere...

In [13]:
common = set.intersection(set(bayarea16.company), set(emdf.company))
common

{'manifold'}

In [14]:
# in California
#golden16 = agencies16[(agencies16['state_l'] == "California")]
#golden15 = agencies15[(agencies15['state_l'] == "California")]
#golden14 = agencies14[(agencies14['state_l'] == "California")]
#golden13 = agencies13[(agencies13['state_l'] == "California")]

In [15]:
#emdf.to_csv('./csv_data/rewritten-itlist.csv')

In [16]:
new = set.intersection(set(tristate16.company), set(emdf.company))
new

{'engine shop', 'factory 360', 'moderne communications'}

- - -
# Ok, let's see if I can iterate across multiple dataframes
### can't fight this feeling there is a smarter way to search for 
### intersections, but I don't know what it is
- - -

## 1. first, a simple 'search for value' function
#### across multiple dataframes, arguments passed in as a set

In [17]:
def searchAgency(sets,searchterm):
    for s in sets:
        print (s[s['company']==searchterm])

In [18]:
sf = [bayarea16, bayarea15, bayarea14, bayarea13]

In [19]:
len(sf)

4

In [20]:
sf[1]

,unnamed: 0,city,state_l,metro,revenue,url,industry,workers,rank,id,yrs_on_list,growth,state_s,company
5,5,San Mateo,California,San Francisco,32945188,drawbridge,Advertising & Marketing,100,6,36636,23484.1623,1,CA,drawbridge
171,171,San Francisco,California,San Francisco,4943130,visually,Advertising & Marketing,38,174,36760,2383.9849,1,CA,visually
206,206,San Francisco,California,San Francisco,15163156,ninthdecimal,Advertising & Marketing,80,210,36789,2028.3743,1,CA,ninthdecimal
429,429,San Francisco,California,San Francisco,4349286,levitate-media,Advertising & Marketing,19,435,26109,1076.7740,2,CA,levitate media
459,459,Corte Madera,California,San Francisco,4348829,sway-group,Advertising & Marketing,9,466,36956,993.2997,1,CA,sway group
675,675,SAN FRANCISCO,California,San Francisco,13906980,six-spoke-media,Advertising & Marketing,33,688,24990,657.2005,2,CA,six spoke media
855,855,Hayward,California,San Francisco,9212755,corefact,Advertising & Marketing,50,868,37162,516.4382,1,CA,corefact
1096,1096,Emeryville,California,San Francisco,19746744,sellpoints,Advertising & Marketing,42,1107,37269,388.5776,1,CA,sellpoints
1381,1381,San Mateo,California,San Francisco,15732367,3q-digital,Advertising & Marketing,111,1393,24606,298.5290,2,CA,3q digital
1639,1639,San Francisco,California,San Francisco,3286837,boca-communications,Advertising & Marketing,30,1653,37488,246.6374,1,CA,boca communications
1694,1694,Corte Madera,California,San Francisco,10276453,mogo-marketing-and-media,Advertising & Marketing,32,1708,37506,237.7795,1,CA,mogo marketing and media
2210,2210,San Francisco,California,San Francisco,8208694,highwire-pr,Advertising & Marketing,52,2226,23516,175.2169,3,CA,highwire pr
2951,2951,San Francisco,California,San Francisco,25916084,dwa-media,Advertising & Marketing,35,2973,25312,117.5056,2,CA,dwa media
3043,3043,Emeryville,California,San Francisco,3038735,bhava-communications,Advertising & Marketing,23,3066,26443,113.1738,2,CA,bhava communications
3048,3048,Berkeley,California,San Francisco,22058329,john-mcneil-studio,Advertising & Marketing,122,3071,37888,113.0245,1,CA,john mcneil studio
3547,3547,San Francisco,California,San Francisco,14062803,launchsquad,Advertising & Marketing,103,3573,1186,88.6070,8,CA,launchsquad
3612,3612,Danville,California,San Francisco,7800000,wingtip-communications,Advertising & Marketing,18,3640,38031,85.7143,1,CA,wingtip communications
4461,4461,San Francisco,California,San Francisco,10207626,eastwick,Advertising & Marketing,53,4490,38219,57.9635,1,CA,eastwick
4677,4677,San Francisco,California,San Francisco,15979216,spark,Advertising & Marketing,66,4707,3197,51.7222,8,CA,spark

In [21]:
searchAgency(sf,'manifold')

      unnamed: 0           city     state_l          metro   revenue  \
3183        3183  San Francisco  California  San Francisco  14863448

           url                 industry  workers  rank     id  yrs_on_list  \
3183  manifold  Advertising & Marketing       16  3183  44172            1

        growth  ifmid  ifiid state_s   company
3183  105.7138      4      5      CA  manifold
Empty DataFrame
Columns: [unnamed: 0, city, state_l, metro, revenue, url, industry, workers, rank, id, yrs_on_list, growth, state_s, company]
Index: []
Empty DataFrame
Columns: [unnamed: 0, city, state_l, metro, revenue, url, industry, workers, rank, id, yrs_on_list, growth, ifmid, ifiid, state_s, company]
Index: []
Empty DataFrame
Columns: [unnamed: 0, city, state_l, metro, revenue, url, industry, workers, rank, id, yrs_on_list, growth, ifmid, ifiid, state_s, company]
Index: []

In [22]:
searchAgency(sf,'bizo')

Empty DataFrame
Columns: [unnamed: 0, city, state_l, metro, revenue, url, industry, workers, rank, id, yrs_on_list, growth, ifmid, ifiid, state_s, company]
Index: []
Empty DataFrame
Columns: [unnamed: 0, city, state_l, metro, revenue, url, industry, workers, rank, id, yrs_on_list, growth, state_s, company]
Index: []
     unnamed: 0           city     state_l          metro   revenue   url  \
965         965  San Francisco  California  San Francisco  37100289  bizo

                    industry  workers  rank     id  yrs_on_list    growth  \
965  Advertising & Marketing      133   968  21035            3  465.0702

     ifmid  ifiid state_s company
965      4      5      CA    bizo
     unnamed: 0           city     state_l          metro   revenue   url  \
546         546  San Francisco  California  San Francisco  22103529  bizo

                    industry  workers  rank     id  yrs_on_list    growth  \
546  Advertising & Marketing      117   552  21035            2  818.9663

     ifmid  ifiid state_s company
546      4      5      CA    bizo

## 2. next, a 'match value across dataframes' function
#### across multiple dataframes, arguments passed in as a set
#### against a single dataframe (column), also an argument

In [28]:
#common = set.intersection(set(bayarea16.company), set(emdf.company))
def matchAgency(sets,comparator):
    for s in sets:
#         print (s.name)
        matches = set.intersection(set(s.company), set(comparator.company))
        print (matches)

In [29]:
matchAgency(sf,emdf)

{'manifold'}
set()
set()
set()

In [30]:
nyc = [tristate16,tristate15,tristate14,tristate13]

In [31]:
matchAgency(nyc,emdf)

{'factory 360', 'moderne communications', 'engine shop'}
{'factory 360'}
{'factory 360', 'engine shop'}
{'mkg', 'invnt'}