In [18]:
import pandas as pd
import numpy as np

In [4]:
# read full dataframe
df = pd.read_csv('gs://datacamp-202518.appspot.com/data/claims/cms_d/PartD_Prescriber_PUF_NPI_13.txt',sep='\t', lineterminator='\n')

# read only the columns I need
# df = pd.read_csv('gs://datacamp-202518.appspot.com/data/claims/cms_d/PartD_Prescriber_PUF_NPI_13.txt',sep='\t', lineterminator='\n')

In [ ]:
# local storage
'''
/home/jupyter/data/cms
PartD_Prescriber_PUF_NPI_17.txt
PartD_Prescriber_PUF_NPI_Drug_17.txt
'''

In [5]:
df.shape

(1049299, 84)

In [6]:
df.head(10)

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,...,beneficiary_male_count,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score\r
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,53.0,NaN,NaN,NaN,0.0,0.0,NaN,79.0,54.0,2.3405\r
1,1003000142,KHALIL,RASHID,NaN,M.D.,M,I,4126 N HOLLAND SYLVANIA RD,SUITE 220,TOLEDO,...,45.0,77.0,NaN,NaN,NaN,0.0,NaN,53.0,48.0,1.607\r
2,1003000167,ESCOBAR,JULIO,E,DDS,M,I,5 PINE CONE RD,NaN,DAYTON,...,13.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.9802\r
3,1003000175,REYES-VASQUEZ,BELINDA,NaN,D.D.S.,F,I,322 N AZUSA AVE STE 202,NaN,LA PUENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
4,1003000183,CYPHERS,DENNIS,J,L.M.P,M,I,6930 52ND AVE W,NaN,TACOMA,...,25.0,35.0,NaN,0.0,NaN,NaN,0.0,36.0,19.0,1.6993\r
5,1003000282,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
6,1003000407,GIRARDI,DAVID,J,D.O.,M,I,456 MAGEE AVE,NaN,PATTON,...,72.0,NaN,0.0,0.0,0.0,NaN,0.0,112.0,73.0,1.6182\r
7,1003000415,WEBSTER,MARSHALL,D,D.C.,M,I,113 CARL VINSON PKWY,NaN,WARNER ROBINS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
8,1003000423,VELOTTA,JENNIFER,A,M.D.,F,I,11100 EUCLID AVE,NaN,CLEVELAND,...,0.0,NaN,NaN,0.0,0.0,0.0,NaN,21.0,18.0,0.8241\r
9,1003000480,ROTHCHILD,KEVIN,B,MD,M,I,12605 E 16TH AVE,NaN,AURORA,...,NaN,14.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.6743\r

In [7]:
list(df)

['npi',
 'nppes_provider_last_org_name',
 'nppes_provider_first_name',
 'nppes_provider_mi',
 'nppes_credentials',
 'nppes_provider_gender',
 'nppes_entity_code',
 'nppes_provider_street1',
 'nppes_provider_street2',
 'nppes_provider_city',
 'nppes_provider_zip5',
 'nppes_provider_zip4',
 'nppes_provider_state',
 'nppes_provider_country',
 'specialty_description',
 'description_flag',
 'medicare_prvdr_enroll_status',
 'total_claim_count',
 'total_30_day_fill_count',
 'total_drug_cost',
 'total_day_supply',
 'bene_count',
 'ge65_suppress_flag',
 'total_claim_count_ge65',
 'total_30_day_fill_count_ge65',
 'total_drug_cost_ge65',
 'total_day_supply_ge65',
 'bene_count_ge65_suppress_flag',
 'bene_count_ge65',
 'brand_suppress_flag',
 'brand_claim_count',
 'brand_drug_cost',
 'generic_suppress_flag',
 'generic_claim_count',
 'generic_drug_cost',
 'other_suppress_flag',
 'other_claim_count',
 'other_drug_cost',
 'mapd_suppress_flag',
 'mapd_claim_count',
 'mapd_drug_cost',
 'pdp_suppress_flag',
 'pdp_claim_count',
 'pdp_drug_cost',
 'lis_suppress_flag',
 'lis_claim_count',
 'lis_drug_cost',
 'nonlis_suppress_flag',
 'nonlis_claim_count',
 'nonlis_drug_cost',
 'opioid_claim_count',
 'opioid_drug_cost',
 'opioid_day_supply',
 'opioid_bene_count',
 'opioid_prescriber_rate',
 'la_opioid_claim_count',
 'la_opioid_drug_cost',
 'la_opioid_day_supply',
 'la_opioid_bene_count',
 'la_opioid_prescriber_rate',
 'antibiotic_claim_count',
 'antibiotic_drug_cost',
 'antibiotic_bene_count',
 'antipsych_ge65_suppress_flag',
 'antipsych_claim_count_ge65',
 'antipsych_drug_cost_ge65',
 'antipsych_bene_ge65_suppress_flg',
 'antipsych_bene_count_ge65',
 'average_age_of_beneficiaries',
 'beneficiary_age_less_65_count',
 'beneficiary_age_65_74_count',
 'beneficiary_age_75_84_count',
 'beneficiary_age_greater_84_count',
 'beneficiary_female_count',
 'beneficiary_male_count',
 'beneficiary_race_white_count',
 'beneficiary_race_black_count',
 'beneficiary_race_asian_pi_count',
 'beneficiary_race_hispanic_count',
 'beneficiary_race_nat_ind_count',
 'beneficiary_race_other_count',
 'beneficiary_nondual_count',
 'beneficiary_dual_count',
 'beneficiary_average_risk_score\r']

In [10]:
impcols = [
'npi',
'nppes_provider_last_org_name',
'nppes_credentials',
'nppes_entity_code',
'nppes_provider_city',
'nppes_provider_zip5',
'nppes_provider_zip4',
'nppes_provider_state',
'specialty_description',
'description_flag',
'brand_suppress_flag',
'brand_claim_count',
'brand_drug_cost',
'generic_suppress_flag',
'generic_claim_count',
'generic_drug_cost',
'antibiotic_claim_count',
'antibiotic_drug_cost',
'antibiotic_bene_count',
]

In [11]:
slim = pd.read_csv('gs://datacamp-202518.appspot.com/data/claims/cms_d/PartD_Prescriber_PUF_NPI_13.txt',sep='\t', lineterminator='\n',usecols = impcols)

In [12]:
list(slim)

['npi',
 'nppes_provider_last_org_name',
 'nppes_credentials',
 'nppes_entity_code',
 'nppes_provider_city',
 'nppes_provider_zip5',
 'nppes_provider_zip4',
 'nppes_provider_state',
 'specialty_description',
 'description_flag',
 'brand_suppress_flag',
 'brand_claim_count',
 'brand_drug_cost',
 'generic_suppress_flag',
 'generic_claim_count',
 'generic_drug_cost',
 'antibiotic_claim_count',
 'antibiotic_drug_cost',
 'antibiotic_bene_count']

In [13]:
slim.head(10)

,npi,nppes_provider_last_org_name,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,specialty_description,description_flag,brand_suppress_flag,brand_claim_count,brand_drug_cost,generic_suppress_flag,generic_claim_count,generic_drug_cost,antibiotic_claim_count,antibiotic_drug_cost,antibiotic_bene_count
0,1003000126,ENKESHAFI,M.D.,I,CUMBERLAND,21502.0,1854.0,MD,Internal Medicine,S,#,NaN,NaN,NaN,309.0,4757.67,81.0,2995.22,63.0
1,1003000142,KHALIL,M.D.,I,TOLEDO,43623.0,3536.0,OH,Anesthesiology,S,NaN,50.0,10127.85,NaN,462.0,10214.70,0.0,0.00,0.0
2,1003000167,ESCOBAR,DDS,I,DAYTON,89403.0,7482.0,NV,Dentist,T,NaN,0.0,0.00,NaN,52.0,328.05,18.0,93.32,15.0
3,1003000175,REYES-VASQUEZ,D.D.S.,I,LA PUENTE,91744.0,4648.0,CA,Dentist,T,*,NaN,NaN,#,NaN,NaN,NaN,NaN,NaN
4,1003000183,CYPHERS,L.M.P,I,TACOMA,98467.0,3207.0,WA,Massage Therapist,T,#,NaN,NaN,NaN,57.0,1248.18,NaN,NaN,NaN
5,1003000282,BLAKEMORE,FNP,I,NASHVILLE,37243.0,1.0,TN,Nurse Practitioner,S,NaN,12.0,1150.75,NaN,48.0,287.26,NaN,NaN,NaN
6,1003000407,GIRARDI,D.O.,I,PATTON,16668.0,1219.0,PA,Family Practice,S,#,NaN,NaN,NaN,365.0,5957.05,141.0,3034.28,110.0
7,1003000415,WEBSTER,D.C.,I,WARNER ROBINS,31088.0,5817.0,GA,Chiropractic,S,NaN,0.0,0.00,NaN,11.0,57.20,0.0,0.00,0.0
8,1003000423,VELOTTA,M.D.,I,CLEVELAND,44106.0,1716.0,OH,Obstetrics/Gynecology,S,NaN,20.0,1485.43,NaN,123.0,3811.16,24.0,349.98,15.0
9,1003000480,ROTHCHILD,MD,I,AURORA,80045.0,2545.0,CO,General Surgery,S,#,NaN,NaN,NaN,35.0,1778.80,NaN,NaN,NaN

In [22]:
specialities = slim.specialty_description.unique()
s = pd.Series(specialities)
s.to_csv('/home/jupyter/data/cms/doctor-specialisms.csv',header=None, index=None)

In [ ]:
impspecialties = [
'Internal Medicine',
'Nurse Practitioner',
'Family Practice',
'Obstetrics/Gynecology',
'Urology',
'Physician Assistant',
'Infectious Disease',
'Preventive Medicine',
'General Practice',
'Clinic/Center',
'Geriatric Medicine',
'Hospital (Dmercs Only)',
'Licensed Practical Nurse',
'Exclusive Provider Organization',
'Case Manager/Care Coordinator',
'Certified Clinical Nurse Specialist',
'Critical Care (Intensivists)',
'Family Medicine',
'Registered Nurse',
'General Acute Care Hospital',
'Multispecialty Clinic/Group Practice',
'Gynecological/Oncology',
'Licensed Vocational Nurse',
'Health Maintenance Organization',
'Community/Behavioral Health',
'Medical Genetics',
'Assisted Living Facility',
'Preferred Provider Organization',
'Obstetrics & Gynecology',
'Nursing Home Administrator',
'Nursing Care',
'Skilled Nursing Facility'
]