In [1]:
import pandas as pd

In [2]:
funnel = pd.read_csv('/home/xavier/data/takeda-email-lease/FUNNEL.csv')
iqvia = pd.read_csv('/home/xavier/data/takeda-email-lease/IQVIA.csv')
dmd = pd.read_csv('/home/xavier/data/takeda-email-lease/DMD.csv')

/home/xavier/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
funnel

,master_contact_id,takeda_id,marketing_segment,hcp_value,tier,entyvio_unrestricted_access,pf_first_name,pf_last_name,pf_email,pf_npi,...,pf_specialty,pf_restrictions,pf_no_npi,pf_pdrp_ama_tak_nocontact,pf_pediatric,pf_no_mailing_address,pf_is_co_or_vt,pf_is_cali,pf_no_email,pf_unusable_email
0,10157257,0001A0000001579,NON-ADOPTER,1,3,0%,Kevin,Jackson,NaN,1.316939e+09,...,Internal Medicine 1,"AMA No Phone,Mail,Fax",f,t,f,f,f,f,t,t
1,10157259,0001A0000001622,NON-ADOPTER,1,3,93%,Donnie,Smith,NaN,1.811939e+09,...,Gastroenterology,"AMA No Phone,Mail,Fax",f,t,f,f,f,f,t,t
2,10157275,0001A0000002556,NON-ADOPTER,1,3,70%,John,Phillips,john.phillips@digestivehlth.com,1.023078e+09,...,Gastroenterology,"AMA No Phone,Mail,Fax",f,t,f,f,f,f,f,t
3,10157294,0001A0000003612,FULL ADOPTER,5,1,95%,Colleen,Schmitt,NaN,1.528024e+09,...,Gastroenterology,"AMA No Phone,Mail,Fax",f,t,f,f,f,f,t,t
4,10157349,0001A0000005861,NON-ADOPTER,1,3,0%,John,Holder,NaN,1.518994e+09,...,Cardiology,"AMA No Phone,Mail,Fax",f,t,f,f,f,f,t,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32908,48885280,0001A0003049291,NON-ADOPTER,1,3,0%,James,Roa,NaN,1.063442e+09,...,Internal Medicine 1,NaN,f,f,f,f,f,f,t,t
32909,48886885,0001A0003050896,FULL ADOPTER,1,3,0%,Roopa,Ram,NaN,1.104950e+09,...,Other 2,NaN,f,f,f,f,f,f,t,t
32910,48890484,0001A0003054496,NON-ADOPTER,1,3,0%,Roza,Yunusova,NaN,1.073967e+09,...,Internal Medicine 1,NaN,f,f,f,f,f,f,t,t
32911,48897063,0001A0003061077,NON-ADOPTER,1,3,0%,Sarah,Bass,NaN,1.457643e+09,...,Oncology,NaN,f,f,f,f,f,f,t,t
32912,48898912,0001A0003062936,NON-ADOPTER,1,3,0%,Yousef,Nasser,NaN,NaN,...,Gastroenterology,NaN,t,f,f,f,f,f,t,t

In [4]:
dmd

,DMD_SEQ,master_contact_id,takeda_id,NPI_#,pf_first_name,pf_last_name,pf_email,pf_state,pf_zip,DMD_NPPA_EMAIL,DMD_PHYS_EMAIL
0,1,10157737,0001A0000020012,1104928043,Keith,Friedenberg,NaN,OH,44060,NaN,E
1,2,10158932,0001A0000070582,1043308570,Arthur,Rabinowitz,arabinowitz@hotmail.com,MA,1805,NaN,E
2,3,10159240,0001A0000084377,1477559664,Richard,Whitlow,NaN,KS,66043,NaN,E
3,4,10159754,0001A0000107480,1235237090,Don,Brinberg,NaN,OH,44060,NaN,E
4,5,10159871,0001A0000110768,1568569382,Jennifer,Rehm,NaN,MA,1805,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...
25851,25852,48225919,0001A0002985016,1578707006,Terri,Giles,NaN,NC,27514,NaN,E
25852,25853,48885280,0001A0003049291,1063442408,James,Roa,NaN,FL,33744,NaN,E
25853,25854,48886885,0001A0003050896,1104949882,Roopa,Ram,NaN,AR,72205,NaN,E
25854,25855,48890484,0001A0003054496,1073966776,Roza,Yunusova,NaN,MN,56573,NaN,E
25855,25856,48897063,0001A0003061077,1457642605,Sarah,Bass,NaN,NC,28562,NaN,E

In [5]:
iqvia

,master_contact_id,takeda_id,pf_npi,pf_first_name,pf_last_name,pf_email,pf_state,pf_zip,JOIN_ID,MATCHL,MATCH_EXPL,HCP_HCE_ID,EMAIL_IND_FLAG
0,11664891,0001A0001063217,1356383889,Fadi,Bdair,NaN,MO,64501,-9990382,ON,NPI only (ON),8197056.0,Y
1,11664947,0001A0000534043,1265474431,Paulo,Pacheco,NaN,NY,10022,-9990381,ON,NPI only (ON),7660193.0,Y
2,11665020,0001A0000569181,1194700534,Richard,Bloomfeld,rbloomfe@wfubmc.edu,NC,27157,-9990378,ON,NPI only (ON),7765251.0,Y
3,11665170,0001A0000044374,1912911843,Jesse,Ezzell Jr,NaN,MS,39440,-9990377,ON,NPI only (ON),7137311.0,Y
4,11665342,0001A0000598081,1972549186,Michael,Ryan,NaN,NC,28262,-9990375,ON,NPI only (ON),7465513.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25851,12028794,0001A0002054142,1700090636,Nathaniel,Krogel,NaN,NC,28655,-9981503,ON,NPI only (ON),8207872.0,Y
25852,12028848,0001A0002061244,1447211990,Christopher,Lynch,NaN,OK,74133,-9981499,ON,NPI only (ON),8157466.0,Y
25853,12029304,0001A0002244109,1386999431,Yazan,Hasan,NaN,IA,52242,-9981493,ON,NPI only (ON),12044627.0,Y
25854,12029424,0001A0002260890,1043356843,Katherine,Khalifeh,NaN,VA,22031,-9981492,ON,NPI only (ON),10287443.0,Y
25855,12029446,0001A0002265137,1144547050,Raghav,Bansal,NaN,NY,11355,-9981491,ON,NPI only (ON),10976022.0,Y

In [6]:
list(iqvia)

['master_contact_id',
 'takeda_id',
 'pf_npi',
 'pf_first_name',
 'pf_last_name',
 'pf_email',
 'pf_state',
 'pf_zip',
 'JOIN_ID',
 'MATCHL',
 'MATCH_EXPL',
 'HCP_HCE_ID',
 'EMAIL_IND_FLAG']

In [7]:
iqviamerged = pd.merge(iqvia,funnel,on='takeda_id',how='left', suffixes=('_left', '_right'))

In [8]:
iqviamerged

,master_contact_id_left,takeda_id,pf_npi_left,pf_first_name_left,pf_last_name_left,pf_email_left,pf_state_left,pf_zip_left,JOIN_ID,MATCHL,...,pf_specialty,pf_restrictions,pf_no_npi,pf_pdrp_ama_tak_nocontact,pf_pediatric,pf_no_mailing_address,pf_is_co_or_vt,pf_is_cali,pf_no_email,pf_unusable_email
0,11664891,0001A0001063217,1356383889,Fadi,Bdair,NaN,MO,64501,-9990382,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
1,11664947,0001A0000534043,1265474431,Paulo,Pacheco,NaN,NY,10022,-9990381,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
2,11665020,0001A0000569181,1194700534,Richard,Bloomfeld,rbloomfe@wfubmc.edu,NC,27157,-9990378,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,f,t
3,11665170,0001A0000044374,1912911843,Jesse,Ezzell Jr,NaN,MS,39440,-9990377,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
4,11665342,0001A0000598081,1972549186,Michael,Ryan,NaN,NC,28262,-9990375,ON,...,Podiatrist,NaN,f,f,f,f,f,f,t,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25851,12028794,0001A0002054142,1700090636,Nathaniel,Krogel,NaN,NC,28655,-9981503,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
25852,12028848,0001A0002061244,1447211990,Christopher,Lynch,NaN,OK,74133,-9981499,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
25853,12029304,0001A0002244109,1386999431,Yazan,Hasan,NaN,IA,52242,-9981493,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t
25854,12029424,0001A0002260890,1043356843,Katherine,Khalifeh,NaN,VA,22031,-9981492,ON,...,Colon & Rectal Surgery,NaN,f,f,f,f,f,f,t,t
25855,12029446,0001A0002265137,1144547050,Raghav,Bansal,NaN,NY,11355,-9981491,ON,...,Gastroenterology,NaN,f,f,f,f,f,f,t,t

In [9]:
list(iqviamerged)

['master_contact_id_left',
 'takeda_id',
 'pf_npi_left',
 'pf_first_name_left',
 'pf_last_name_left',
 'pf_email_left',
 'pf_state_left',
 'pf_zip_left',
 'JOIN_ID',
 'MATCHL',
 'MATCH_EXPL',
 'HCP_HCE_ID',
 'EMAIL_IND_FLAG',
 'master_contact_id_right',
 'marketing_segment',
 'hcp_value',
 'tier',
 'entyvio_unrestricted_access',
 'pf_first_name_right',
 'pf_last_name_right',
 'pf_email_right',
 'pf_npi_right',
 'pf_address1',
 'pf_address2',
 'pf_city',
 'pf_state_right',
 'pf_zip_right',
 'pf_specialty',
 'pf_restrictions',
 'pf_no_npi',
 'pf_pdrp_ama_tak_nocontact',
 'pf_pediatric',
 'pf_no_mailing_address',
 'pf_is_co_or_vt',
 'pf_is_cali',
 'pf_no_email',
 'pf_unusable_email']

In [10]:
iqviamerged.to_csv('/home/xavier/data/takeda-email-lease/IQVIA-FUNNEL-TAKID.csv')

In [11]:
dmdmerged = pd.merge(dmd,funnel,on='takeda_id',how='left', suffixes=('_left', '_right'))
list(dmdmerged)

['DMD_SEQ',
 'master_contact_id_left',
 'takeda_id',
 'NPI_#',
 'pf_first_name_left',
 'pf_last_name_left',
 'pf_email_left',
 'pf_state_left',
 'pf_zip_left',
 'DMD_NPPA_EMAIL',
 'DMD_PHYS_EMAIL',
 'master_contact_id_right',
 'marketing_segment',
 'hcp_value',
 'tier',
 'entyvio_unrestricted_access',
 'pf_first_name_right',
 'pf_last_name_right',
 'pf_email_right',
 'pf_npi',
 'pf_address1',
 'pf_address2',
 'pf_city',
 'pf_state_right',
 'pf_zip_right',
 'pf_specialty',
 'pf_restrictions',
 'pf_no_npi',
 'pf_pdrp_ama_tak_nocontact',
 'pf_pediatric',
 'pf_no_mailing_address',
 'pf_is_co_or_vt',
 'pf_is_cali',
 'pf_no_email',
 'pf_unusable_email']

In [13]:
dmdmerged.to_csv('/home/xavier/data/takeda-email-lease/DMD-FUNNEL-TAKID.csv')

In [15]:
print (f'IQVIA, merged = {len(iqviamerged)}, while DMD, merged = {len(dmdmerged)} ')

IQVIA, merged = 25856, while DMD, merged = 25856